version: "3.8"

services:
  data_quality_tool:
    build:
      context: ./data_quality_tool
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}

  datacatalog_db:
    image: postgres:15
    volumes:
      - ./.stored_data/datacatalogdb:/var/lib/postgresql/data
    hostname: datacatalog_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p 5432
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8090:8090"
    environment:
      ### Database ###
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      ### Frontend ###
      - PUBLIC_HOST=${PUBLIC_HOST}
      - DQT_URL=${DQT_URL}
      ### Keycloak ###
      - AUTHENTICATION=${AUTHENTICATION}
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
    depends_on:
      datacatalog_db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80" # Expose the frontend on port 80
    depends_on:
      - backend
