[tool.poetry]
name = "datacatalog"
version = "0.1.0"
description = ""
authors = ["Kostas Filippopolitis <kfilippopolitis@athenarc.gr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

