# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: default
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-local-storage

---

# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.datacatalogDb.password }}" # Replace with a secure password
            - name: POSTGRES_USER
              value: "{{ .Values.datacatalogDb.user }}" # Replace with your preferred username
            - name: POSTGRES_DB
              value: "{{ .Values.datacatalogDb.db }}" # Replace with your preferred database name
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc

---

# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: datacatalogdb
  namespace: default
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-local-storage
  hostPath:
    path: /data/db

