# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: db
  {{- if .Values.managed_cluster }}
  annotations:
    # tells Argo CD: do not prune (delete) this resource
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.datacatalogDb.storage }}
  storageClassName: {{- if .Values.managed_cluster }} {{ .Values.storageClasses.managed }} {{- else }} {{ .Values.storageClasses.local }} {{- end }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.datacatalogDb.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datacatalog-secrets
                  key: db.password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: datacatalog-secrets
                  key: db.user
            - name: POSTGRES_DB
              value: {{ .Values.datacatalogDb.db | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc

---

# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: datacatalogdb
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db