apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.datacatalogDb.storage }}
  storageClassName: |
    {{- if .Values.managed_cluster }}
    ceph-corbo-cephfs
    {{- else }}
    k8s-local-storage
    {{- end }}

---

{{- if not .Values.managed_cluster }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-local-storage
  hostPath:
    path: /data/db
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.datacatalogDb.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.datacatalogDb.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.datacatalogDb.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.datacatalogDb.db | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: datacatalogdb
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db