apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.datacatalog_images.repository }}/datacatalog_frontend:{{ .Values.datacatalog_images.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- if .Values.managed_cluster }}
      nodePort: 30080  # Static NodePort for frontend
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:

  name: datacatalog-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.frontend.ingress }}
    cert-manager.io/cluster-issuer: {{ .Values.frontend.cert_manager }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName:  {{ .Values.frontend.ingress }}
  tls:
    - hosts:
      - {{ .Values.backend.publicHost }}
      secretName: datacatalog-tls
  rules:
    - host: {{ .Values.backend.publicHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}