# Configuration for development purposes
### EMBEDDED SERVER CONFIGURATION ###
server:
  servlet:
    context-path: "/services"
  port: 8090
  forward-headers-strategy: native

### AUTHENTICATION ###
authentication:
  enabled: 1
  domain_expert: "DC_DOMAIN_EXPERT"

### LOG LEVELS ###
logging:
  level:
    root: "INFO"
    eu:
      ebrainsv2: "DEBUG"


### DATABASE CONFIGURATION ###
spring:
  datasource:
    url: jdbc:postgresql://datacatalogdb:5432/postgres
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://datacatalogdb:5432/postgres
    user: postgres
    password: test
    baseline-on-migrate: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://iam.ebrains.eu/auth/realms/MIP # Keycloak issuer URI
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: datacatalog
            client-secret: <>
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"  # must match Keycloak's redirect URI
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://iam.ebrains.eu/auth/realms/MIP
            user-name-attribute: preferred_username

app:
  frontend:
    auth-callback-url: "http://localhost:4200/auth-callback"
    base-url: "http://localhost:4200"
  data_quality_tool:
    json-to-excel-url: "http://data_quality_tool:8000/json-to-excel"
    excel-to-json-url: "http://data_quality_tool:8000/excel-to-json"

