name: Build & Push images on Release

on:
  release:
    types: [published]

env:
  DOCKERHUB_ORG: madgik
  APP: datacatalog

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: backend
            context: ./backend
          - component: frontend
            context: ./frontend
          - component: data_quality_tool
            context: ./data_quality_tool

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from release tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare image name
        run: |
          echo "IMAGE=${{ env.DOCKERHUB_ORG }}/${{ env.APP }}_${{ matrix.component }}" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
